version: "3.1"
services:
  db:
    container_name: postgresdb
    image: postgres:14
    restart: always
    privileged: true
    environment:
      - POSTGRES_USER=leoantony
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=intrazeal
    volumes:
      - ./postgres-data:/mnt/e/codee/e-commerce/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data: